
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '{}' NOT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '{}' NOT NULL;
ALTER TABLE templates ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '{}' NOT NULL;
